replicaCount: 2
image:
  repository: registry.arc-center.run/silverkeytech/skblogsystem
  pullPolicy: IfNotPresent
  tag: skblogsystem-prod-latest

resources:
  requests:
    cpu: 60m
    memory: 60M
